export const MOVIES_LIST_REQUEST = 'MOVIES_LIST_REQUEST';
export const MOVIES_LIST_SUCCESS = 'MOVIES_LIST_SUCCESS';
export const MOVIES_LIST_FAIL = 'MOVIES_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const MOVIES_CREATE_REQUEST = 'MOVIES_CREATE_REQUEST';
export const MOVIES_CREATE_SUCCESS = 'MOVIES_CREATE_SUCCESS';
export const MOVIES_CREATE_FAIL = 'MOVIES_CREATE_FAIL';

export const MOVIES_DELETE_REQUEST = 'MOVIES_DELETE_REQUEST';
export const MOVIES_DELETE_SUCCESS = 'MOVIES_DELETE_SUCCESS';
export const MOVIES_DELETE_FAIL = 'MOVIES_DELETE_FAIL';
